### ISSUE TITLE
feat: custom format log

### ISSUE THREAD

**Issue by RodrigoDornelles** [fastify/one-line-logger#33]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

ability to change the format of the logs

### Motivation

I'm working on standardizing logs at my work, and I chose to choose **line protocol** from influxdb, if there is a field for me to pass a custom function I would be able to do it well!

 * <https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/>

### Example

```javascript
const server = fastify({
  logger: {
    transport: {
      target: "@fastify/one-line-logger",
    },
    customLevels: {
      foo: 35,
      bar: 45,
    },
    format: (log) => `${log.level.name} error="${log.message}" ${(new Date).getTime()/1000}` 
  },
});
```

**Comment by mcollina** [comment]
I think you'd need to create your own transport for that. You can use this repo as the template.
