### ISSUE TITLE
Add colors!

### ISSUE THREAD

**Issue by mcollina** [fastify/one-line-logger#35]
As titled, it would be awesome if this transport added colors!

**Comment by Uzlopak** [comment]
Do you have a code example on how you would use it?
How many colors?

**Comment by mcollina** [comment]
Maybe check out pino-colada and pino-pretty for inspiration?

**Comment by mcollina** [comment]
I've been trying to have one-line-logger be colored by default, but I couldn't make it work.

What I would expect it's something slightly different and "nicer" to read.

This is the output of pino-pretty:

![Screenshot 2024-04-30 at 12 51 33](https://github.com/fastify/one-line-logger/assets/52195/fa6da905-b7da-4fb1-b528-e0bca8426211)

I would expect this module to retain the color of the level.

This is with the default settings:

![Screenshot 2024-04-30 at 12 53 11](https://github.com/fastify/one-line-logger/assets/52195/135a5f70-ad93-47c7-bef2-b8eed7f093de)

However I need to force a `colorize: true` option to get it to where it should be:

```js
const fastify = require('fastify')({
  logger: {
    transport: {
      target: './index.js',
      options: {
        colorize: true,
      }
    }
  }
})
```

![Screenshot 2024-04-30 at 12 55 23](https://github.com/fastify/one-line-logger/assets/52195/30c23171-22c4-424b-b94c-af47eeddf4b1)

There should not be a need to foce `colorize: true`.

**Comment by mcollina** [comment]
cc @synapse @simoneb

**Comment by synapse** [comment]
@mcollina @simoneb create a new PR here #42 that enables colors automatically.
