### ISSUE TITLE
Updating for v5

### ISSUE THREAD

**Issue by Gesma94** [fastify/one-line-logger#39]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

👋 I'm Matteo, and would like to work on this.
Coming from Fastify issue #5116 (https://github.com/fastify/fastify/issues/5116)

From what I've understood, I need to:
- Update NPM packages (standard, tap, fastify)
- Update the workflow to use the version 4.1.0 of plugins-ci
- Update `tap` configuration

If there's anything I'm missing, please do let me know

**Comment by gurgunday** [comment]
`next` branch created

https://github.com/fastify/one-line-logger/tree/next

**Comment by Fdawgs** [comment]
Closed by #40
