### ISSUE TITLE
Add request id in the log?

### ISSUE THREAD

**Issue by wtchangdm** [fastify/one-line-logger#5]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hi, I am developing some sort of proxy for internal use. This logger is a good fit for users who want to try on their local environment for better readability.

However, the default format doesn't append request id, which could make user slightly harder to identify the request.

### Motivation

Showing request id can be useful to identify what's happening during a specific request.
However, when request id is rather long (e.g., front-end proxy sent a `request-id` header), it can be noisy.

Please let me know what do you think!

### Example

Instead of:
```
YYYY-MM-dd HH:mm:ss.SSSTZ - <level> - <method> <route path> - <message>
```

Maybe we could use:
```
YYYY-MM-dd HH:mm:ss.SSSTZ - <level> - <req id> - <method> <route path> - <message>
```

**Comment by mcollina** [comment]
This logger is configuration of `pino-pretty`, check out the source code: https://github.com/fastify/one-line-logger/blob/master/src/index.js.

If you want to customize this, it's easy to fork and adapt to your needs.

**Comment by wtchangdm** [comment]
Sure, thanks @mcollina
