### ISSUE TITLE
Support CustomLevels

### ISSUE THREAD

**Issue by Uzlopak** [fastify/one-line-logger#7]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

One-Line-Logger should support CustomLogLevels

### Motivation

While refactoring I realized, that only the default loglevels are supported. When somebody uses a custom log level i assume, that you get "undefined" for the log level. I assume we can passthrough the pino pretty option `customLevels`, parse it and merge it with the default values.

**Comment by Fdawgs** [comment]
> Dont know why is it not automagically linked on this issue

You need to write things like `closes #7` or `fixes #7` for it to link. I've linked it anyway. 😄
